################################################################################
#
# kernel module bdsdmac backports
#
################################################################################

KERNEL_MODULE_BDSDMAC_BACKPORTS_VERSION = 11.171.0.28
KERNEL_MODULE_BDSDMAC_BACKPORTS_SITE = "https://github.com/LairdCP/BDSDMAC-Release-Packages/releases/download/LRD-REL-"$(KERNEL_MODULE_BDSDMAC_BACKPORTS_VERSION)
KERNEL_MODULE_BDSDMAC_BACKPORTS_SOURCE = backports-laird-$(KERNEL_MODULE_BDSDMAC_BACKPORTS_VERSION).tar.bz2
KERNEL_MODULE_BDSDMAC_BACKPORTS_LICENSE = GPL-2.0
KERNEL_MODULE_BDSDMAC_BACKPORTS_DEPENDENCIES = linux
KERNEL_MODULE_BDSDMAC_BACKPORTS_KCONFIG_FILE = $(KERNEL_MODULE_BDSDMAC_BACKPORTS_DIR)/defconfigs/bdimx6
KERNEL_MODULE_BDSDMAC_BACKPORTS_KCONFIG_OPTS = $(KERNEL_MODULE_BDSDMAC_BACKPORTS_MAKE_OPTS)
KERNEL_MODULE_BDSDMAC_BACKPORTS_MAKE_ENV = $(HOST_MAKE_ENV)
KERNEL_MODULE_BDSDMAC_BACKPORTS_MINIMAL_KVER_MAJOR = 3
KERNEL_MODULE_BDSDMAC_BACKPORTS_MINIMAL_KVER_MINOR = 0

KERNEL_MODULE_BDSDMAC_BACKPORTS_KCONFIG_DEPENDENCIES = \
	$(BR2_BISON_HOST_DEPENDENCY) \
	$(BR2_FLEX_HOST_DEPENDENCY)

KERNEL_MODULE_BDSDMAC_BACKPORTS_MAKE_OPTS = \
	LEX=flex \
	YACC=bison \
	BACKPORT_DIR=$(@D) \
	KLIB_BUILD=$(LINUX_DIR) \
	KLIB=$(TARGET_DIR)/lib/modules/$(LINUX_VERSION_PROBED) \
	INSTALL_MOD_DIR=updates \
	`sed -r -e '/^\#/d;' $(@D)/.config`

KERNEL_MODULE_BDSDMAC_BACKPORTS_MODULE_MAKE_OPTS = $(KERNEL_MODULE_BDSDMAC_BACKPORTS_MAKE_OPTS)

define KERNEL_MODULE_BDSDMAC_BACKPORTS_KCONFIG_FIXUP_CMDS
	rm -f $(@D)/backport-include/backport/autoconf.h
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) $(KERNEL_MODULE_BDSDMAC_BACKPORTS_MAKE_OPTS) backport-include/backport/autoconf.h
endef

$(eval $(kernel-module))
$(eval $(kconfig-package))

$(KERNEL_MODULE_BDSDMAC_BACKPORTS_DIR)/$(KERNEL_MODULE_BDSDMAC_BACKPORTS_KCONFIG_STAMP_DOTCONFIG): $(KERNEL_MODULE_BDSDMAC_BACKPORTS_DIR)/.stamp_check_kernel_version

.SECONDEXPANSION:
$(KERNEL_MODULE_BDSDMAC_BACKPORTS_DIR)/.stamp_check_kernel_version: $$(LINUX_DIR)/$$(LINUX_KCONFIG_STAMP_DOTCONFIG) | linux
	$(Q)KVER=$(LINUX_VERSION_PROBED); \
	MIN_KVER_MAJOR=$(KERNEL_MODULE_BDSDMAC_BACKPORTS_MINIMAL_KVER_MAJOR); \
	MIN_KVER_MINOR=$(KERNEL_MODULE_BDSDMAC_BACKPORTS_MINIMAL_KVER_MINOR); \
	KVER_MAJOR=`echo $${KVER} | sed 's/^\([0-9]*\)\..*/\1/'`; \
	KVER_MINOR=`echo $${KVER} | sed 's/^[0-9]*\.\([0-9]*\).*/\1/'`; \
	if [ $${KVER_MAJOR} -lt $(KERNEL_MODULE_BDSDMAC_BACKPORTS_MINIMAL_KVER_MAJOR) \
		-o \( $${KVER_MAJOR} -eq $(KERNEL_MODULE_BDSDMAC_BACKPORTS_MINIMAL_KVER_MAJOR) \
			-a $${KVER_MINOR} -lt $(KERNEL_MODULE_BDSDMAC_BACKPORTS_MINIMAL_KVER_MINOR) \
		\) ]; then \
		printf "Linux version '%s' is too old for linux-backports (needs %s.%s or later)\n" \
			"$${KVER}" \
			"$(KERNEL_MODULE_BDSDMAC_BACKPORTS_MINIMAL_KVER_MAJOR)" \
			"$(KERNEL_MODULE_BDSDMAC_BACKPORTS_MINIMAL_KVER_MINOR)"; \
		exit 1; \
	fi
	$(Q)touch $(@)

$(KERNEL_MODULE_BDSDMAC_BACKPORTS_DIR)/.stamp_built: $$(LINUX_DIR)/.stamp_built | linux
